import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Menu } from '../components/Menu';
import { Footer } from "@/components/Footer";

const monserrat = Montserrat({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.className} antialiased bg-gradient-to-b from-background-tertiary to-background-primary  text-color-text-secondary `}
        
      >
        <Menu />
        <main className="min-h-screen px-4 md:px-32 max-w-6xl mx-auto">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
